In [1]:
import pandas as pd
from glob import glob
import numpy as np

In [2]:
# list all files that match a pattern and sort results
stock_files = sorted(glob('raw_data/data_*.csv'))
stock_files

['raw_data\\data_1.csv',
 'raw_data\\data_10.csv',
 'raw_data\\data_11.csv',
 'raw_data\\data_12.csv',
 'raw_data\\data_13.csv',
 'raw_data\\data_14.csv',
 'raw_data\\data_15.csv',
 'raw_data\\data_16.csv',
 'raw_data\\data_17.csv',
 'raw_data\\data_18.csv',
 'raw_data\\data_19.csv',
 'raw_data\\data_2.csv',
 'raw_data\\data_20.csv',
 'raw_data\\data_21.csv',
 'raw_data\\data_22.csv',
 'raw_data\\data_23.csv',
 'raw_data\\data_24.csv',
 'raw_data\\data_25.csv',
 'raw_data\\data_26.csv',
 'raw_data\\data_27.csv',
 'raw_data\\data_28.csv',
 'raw_data\\data_29.csv',
 'raw_data\\data_3.csv',
 'raw_data\\data_30.csv',
 'raw_data\\data_31.csv',
 'raw_data\\data_4.csv',
 'raw_data\\data_5.csv',
 'raw_data\\data_6.csv',
 'raw_data\\data_7.csv',
 'raw_data\\data_8.csv',
 'raw_data\\data_9.csv']

In [3]:
# Use a generator expression to read the files, assign(), to create a new column, and concat Dataframes 
df = pd.concat((pd.read_csv(file).assign(filename = file)
          for file in stock_files), ignore_index = True)
df.head()

,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,FIPS,Incident_Rate,People_Tested,People_Hospitalized,Mortality_Rate,UID,ISO3,Testing_Rate,Hospitalization_Rate,filename
0,Alabama,US,4/20/2020 11:36:47 PM,32.3182,-86.9023,5079.0,163.0,NaN,4916.0,1.0,108.319718,45900.0,641.0,3.209293,84000001.0,USA,978.908259,12.620595,raw_data\data_1.csv
1,Alaska,US,4/20/2020 11:36:47 PM,61.3707,-152.4044,321.0,9.0,161.0,312.0,2.0,53.701470,10124.0,46.0,2.803738,84000002.0,USA,1693.687484,14.330218,raw_data\data_1.csv
2,American Samoa,US,NaN,-14.2710,-170.1320,0.0,0.0,NaN,NaN,60.0,0.000000,3.0,NaN,NaN,16.0,ASM,5.391708,NaN,raw_data\data_1.csv
3,Arizona,US,4/20/2020 11:36:47 PM,33.7298,-111.4312,5068.0,191.0,1155.0,4877.0,4.0,69.627656,54500.0,637.0,3.768745,84000004.0,USA,748.758332,12.569061,raw_data\data_1.csv
4,Arkansas,US,4/20/2020 11:36:47 PM,34.9697,-92.3731,1973.0,41.0,749.0,1932.0,5.0,76.206235,26553.0,291.0,2.078054,84000005.0,USA,1025.597647,14.749113,raw_data\data_1.csv

In [37]:
df = df.rename(columns={"Province_State": "state"})
df.head()

,state,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,FIPS,Incident_Rate,People_Tested,People_Hospitalized,Mortality_Rate,UID,ISO3,Testing_Rate,Hospitalization_Rate,filename
0,Alabama,US,4/20/2020 11:36:47 PM,32.3182,-86.9023,5079.0,163.0,NaN,4916.0,1.0,108.319718,45900.0,641.0,3.209293,84000001.0,USA,978.908259,12.620595,raw_data\data_1.csv
1,Alaska,US,4/20/2020 11:36:47 PM,61.3707,-152.4044,321.0,9.0,161.0,312.0,2.0,53.701470,10124.0,46.0,2.803738,84000002.0,USA,1693.687484,14.330218,raw_data\data_1.csv
2,American Samoa,US,NaN,-14.2710,-170.1320,0.0,0.0,NaN,NaN,60.0,0.000000,3.0,NaN,NaN,16.0,ASM,5.391708,NaN,raw_data\data_1.csv
3,Arizona,US,4/20/2020 11:36:47 PM,33.7298,-111.4312,5068.0,191.0,1155.0,4877.0,4.0,69.627656,54500.0,637.0,3.768745,84000004.0,USA,748.758332,12.569061,raw_data\data_1.csv
4,Arkansas,US,4/20/2020 11:36:47 PM,34.9697,-92.3731,1973.0,41.0,749.0,1932.0,5.0,76.206235,26553.0,291.0,2.078054,84000005.0,USA,1025.597647,14.749113,raw_data\data_1.csv

In [38]:
df1=df.drop(columns= ['filename','UID'])
df1

,state,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,FIPS,Incident_Rate,People_Tested,People_Hospitalized,Mortality_Rate,ISO3,Testing_Rate,Hospitalization_Rate
0,Alabama,US,4/20/2020 11:36:47 PM,32.3182,-86.9023,5079.0,163.0,NaN,4916.0,1.0,108.319718,45900.0,641.0,3.209293,USA,978.908259,12.620595
1,Alaska,US,4/20/2020 11:36:47 PM,61.3707,-152.4044,321.0,9.0,161.0,312.0,2.0,53.701470,10124.0,46.0,2.803738,USA,1693.687484,14.330218
2,American Samoa,US,NaN,-14.2710,-170.1320,0.0,0.0,NaN,NaN,60.0,0.000000,3.0,NaN,NaN,ASM,5.391708,NaN
3,Arizona,US,4/20/2020 11:36:47 PM,33.7298,-111.4312,5068.0,191.0,1155.0,4877.0,4.0,69.627656,54500.0,637.0,3.768745,USA,748.758332,12.569061
4,Arkansas,US,4/20/2020 11:36:47 PM,34.9697,-92.3731,1973.0,41.0,749.0,1932.0,5.0,76.206235,26553.0,291.0,2.078054,USA,1025.597647,14.749113
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1973,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1974,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1975,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1976,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1977,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [39]:
df2=df1.dropna(how='all')
df2

,state,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,FIPS,Incident_Rate,People_Tested,People_Hospitalized,Mortality_Rate,ISO3,Testing_Rate,Hospitalization_Rate
0,Alabama,US,4/20/2020 11:36:47 PM,32.3182,-86.9023,5079.0,163.0,NaN,4916.0,1.0,108.319718,45900.0,641.0,3.209293,USA,978.908259,12.620595
1,Alaska,US,4/20/2020 11:36:47 PM,61.3707,-152.4044,321.0,9.0,161.0,312.0,2.0,53.701470,10124.0,46.0,2.803738,USA,1693.687484,14.330218
2,American Samoa,US,NaN,-14.2710,-170.1320,0.0,0.0,NaN,NaN,60.0,0.000000,3.0,NaN,NaN,ASM,5.391708,NaN
3,Arizona,US,4/20/2020 11:36:47 PM,33.7298,-111.4312,5068.0,191.0,1155.0,4877.0,4.0,69.627656,54500.0,637.0,3.768745,USA,748.758332,12.569061
4,Arkansas,US,4/20/2020 11:36:47 PM,34.9697,-92.3731,1973.0,41.0,749.0,1932.0,5.0,76.206235,26553.0,291.0,2.078054,USA,1025.597647,14.749113
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1965,Washington,US,4/29/2020 2:32:33 AM,47.4009,-121.4905,13842.0,786.0,NaN,13056.0,53.0,183.352247,179679.0,NaN,5.678370,USA,2380.042501,NaN
1966,West Virginia,US,4/29/2020 2:32:33 AM,38.4912,-80.9545,1095.0,38.0,481.0,1057.0,54.0,82.766565,43055.0,NaN,3.470320,USA,3254.351103,NaN
1967,Wisconsin,US,4/29/2020 2:32:33 AM,44.2685,-89.6165,6289.0,300.0,NaN,5989.0,55.0,121.536645,69824.0,1456.0,4.770234,USA,1349.367899,23.151534
1968,Wyoming,US,4/29/2020 2:32:33 AM,42.7560,-107.3025,536.0,7.0,343.0,529.0,56.0,107.795029,8615.0,56.0,1.305970,USA,1732.563752,10.447761
1969,Recovered,US,4/29/2020 2:32:33 AM,NaN,NaN,0.0,0.0,115936.0,-115936.0,NaN,NaN,NaN,NaN,NaN,USA,NaN,NaN

In [40]:

df3 = df2.replace(np.nan, '0', regex=True)
df3

,state,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,FIPS,Incident_Rate,People_Tested,People_Hospitalized,Mortality_Rate,ISO3,Testing_Rate,Hospitalization_Rate
0,Alabama,US,4/20/2020 11:36:47 PM,32.3182,-86.9023,5079.0,163.0,0,4916,1,108.32,45900,641,3.20929,USA,978.908,12.6206
1,Alaska,US,4/20/2020 11:36:47 PM,61.3707,-152.404,321.0,9.0,161,312,2,53.7015,10124,46,2.80374,USA,1693.69,14.3302
2,American Samoa,US,0,-14.271,-170.132,0.0,0.0,0,0,60,0,3,0,0,ASM,5.39171,0
3,Arizona,US,4/20/2020 11:36:47 PM,33.7298,-111.431,5068.0,191.0,1155,4877,4,69.6277,54500,637,3.76875,USA,748.758,12.5691
4,Arkansas,US,4/20/2020 11:36:47 PM,34.9697,-92.3731,1973.0,41.0,749,1932,5,76.2062,26553,291,2.07805,USA,1025.6,14.7491
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1965,Washington,US,4/29/2020 2:32:33 AM,47.4009,-121.49,13842.0,786.0,0,13056,53,183.352,179679,0,5.67837,USA,2380.04,0
1966,West Virginia,US,4/29/2020 2:32:33 AM,38.4912,-80.9545,1095.0,38.0,481,1057,54,82.7666,43055,0,3.47032,USA,3254.35,0
1967,Wisconsin,US,4/29/2020 2:32:33 AM,44.2685,-89.6165,6289.0,300.0,0,5989,55,121.537,69824,1456,4.77023,USA,1349.37,23.1515
1968,Wyoming,US,4/29/2020 2:32:33 AM,42.756,-107.302,536.0,7.0,343,529,56,107.795,8615,56,1.30597,USA,1732.56,10.4478
1969,Recovered,US,4/29/2020 2:32:33 AM,0,0,0.0,0.0,115936,-115936,0,0,0,0,0,USA,0,0

In [41]:
df3.dtypes

state                    object
Country_Region           object
Last_Update              object
Lat                      object
Long_                    object
Confirmed               float64
Deaths                  float64
Recovered                object
Active                   object
FIPS                     object
Incident_Rate            object
People_Tested            object
People_Hospitalized      object
Mortality_Rate           object
ISO3                     object
Testing_Rate             object
Hospitalization_Rate     object
dtype: object

In [42]:
df3=df3.astype({'Recovered':'float64'})
df3=df3.astype({'Active':'float64'})
df3=df3.astype({'People_Tested':'float64'})
df3=df3.astype({'People_Hospitalized':'float64'})

In [46]:
df4=df3.groupby(['state']).sum()
df4

,Confirmed,Deaths,Recovered,Active,People_Tested,People_Hospitalized
state,,,,,,
Alabama,268365.0,10469.0,0.0,257896.0,3271388.0,33973.0
Alaska,11345.0,294.0,8568.0,4545.0,726773.0,261.0
American Samoa,0.0,0.0,0.0,0.0,1873.0,0.0
Arizona,296916.0,13583.0,66156.0,230418.0,3143680.0,40766.0
Arkansas,111560.0,2345.0,67785.0,51013.0,1792689.0,12537.0
California,1833427.0,73742.0,0.0,1759685.0,25160433.0,39006.0
Colorado,529952.0,27484.0,73634.0,439770.0,2703381.0,93679.0
Connecticut,940155.0,79582.0,107815.0,752758.0,3589061.0,203891.0
Delaware,171738.0,5875.0,61578.0,112275.0,853420.0,2297.0
Diamond Princess,1519.0,0.0,0.0,1519.0,0.0,0.0
District of Columbia,163811.0,8224.0,24496.0,137589.0,789052.0,3216.0
Florida,1158800.0,45876.0,0.0,1112924.0,14713034.0,203058.0
Georgia,926323.0,39075.0,0.0,887248.0,6500635.0,170561.0
Grand Princess,3193.0,84.0,0.0,3109.0,0.0,0.0
Guam,4545.0,155.0,3873.0,1757.0,96346.0,20.0
Hawaii,19254.0,486.0,16284.0,7096.0,1055712.0,2259.0
Idaho,65570.0,1977.0,38795.0,33301.0,883668.0,5928.0
Illinois,2038238.0,89842.0,0.0,1948396.0,11278576.0,37711.0
Indiana,643923.0,38786.0,0.0,605137.0,3756093.0,57122.0
Iowa,298931.0,6724.0,126852.0,182643.0,1929441.0,2139.0
Kansas,171053.0,4827.0,7999.0,158493.0,1304702.0,18091.0
Kentucky,174454.0,8361.0,61799.0,118051.0,2395149.0,47446.0
Louisiana,929062.0,64124.0,545117.0,416511.0,6070947.0,13847.0
Maine,39690.0,1797.0,23307.0,19682.0,666914.0,5719.0
Maryland,848156.0,42720.0,58074.0,758599.0,4307101.0,163249.0
Massachusetts,2117150.0,128884.0,0.0,1988266.0,10203675.0,205919.0
Michigan,1356363.0,125517.0,484164.0,804577.0,7609968.0,24982.0
Minnesota,269102.0,14325.0,151289.0,119616.0,2951437.0,42561.0
Mississippi,254002.0,10951.0,114931.0,131533.0,2519513.0,41951.0
Missouri,275959.0,13197.0,0.0,262762.0,3095815.0,6844.0
Montana,14119.0,473.0,12033.0,4824.0,574281.0,1910.0
Nebraska,194746.0,2511.0,0.0,192235.0,1171087.0,0.0
Nevada,173926.0,8422.0,4840.0,160764.0,1651088.0,0.0
New Hampshire,81748.0,3225.0,30986.0,54121.0,899859.0,8826.0
New Jersey,3911562.0,248916.0,398892.0,3295038.0,9940602.0,55579.0
New Mexico,128423.0,5137.0,32264.0,96949.0,2599100.0,20068.0
New York,9761342.0,769847.0,1526945.0,7760514.0,32423342.0,2102778.0
North Carolina,401661.0,14853.0,98716.0,288092.0,5085805.0,3577.0
North Dakota,40103.0,881.0,20384.0,21856.0,1122676.0,3036.0
Northern Mariana Islands,501.0,62.0,366.0,185.0,51182.0,0.0
Ohio,655841.0,35440.0,0.0,620401.0,5391173.0,122270.0
Oklahoma,127745.0,7440.0,88804.0,51399.0,2540011.0,23375.0
Oregon,88965.0,3496.0,21703.0,63766.0,2090062.0,19031.0
Pennsylvania,1639300.0,96234.0,0.0,1543066.0,7876854.0,21988.0
Puerto Rico,59835.0,3059.0,0.0,56776.0,206183.0,0.0
Recovered,0.0,0.0,959621.0,-959621.0,0.0,0.0
Rhode Island,300891.0,10763.0,20118.0,273778.0,2403877.0,31857.0
South Carolina,212304.0,8633.0,126570.0,108747.0,2355225.0,35294.0
South Dakota,90829.0,806.0,58284.0,43143.0,640853.0,6663.0
Tennessee,407306.0,7073.0,208641.0,235345.0,6905414.0,35816.0
Texas,1072342.0,29370.0,538421.0,597477.0,13677437.0,12533.0
Utah,168510.0,1769.0,77942.0,101837.0,3932578.0,13921.0
Vermont,27659.0,1543.0,20269.0,14412.0,565653.0,307.0
Virgin Islands,1974.0,137.0,1693.0,641.0,31112.0,0.0
Virginia,630373.0,21633.0,84359.0,541190.0,3796192.0,121941.0
Washington,484369.0,26711.0,0.0,457658.0,6679574.0,7397.0
West Virginia,38284.0,1484.0,20086.0,20817.0,1645004.0,767.0
Wisconsin,267930.0,11037.0,109113.0,147780.0,3080999.0,51869.0
Wyoming,18715.0,217.0,12362.0,9158.0,362383.0,1887.0